In [18]:
import numpy as np
import pandas as pd

In [97]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [22]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a.ndim

1

In [24]:
b.ndim

2

In [25]:
a.shape

(9,)

In [26]:
b.shape


(2, 5)

In [27]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('int32')

In [33]:
a.itemsize

2

In [32]:
a.nbytes

18

## Accessing / changing speific elements, rows, columns etc

In [35]:
arr = np.array([[1,2,3,4,5,6,7,8,9],[11,12,13,14,15,16,17,18,19]])
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


In [36]:
arr[1,5]

16

#### Indexing starts from 0 -> points to be remembered ! 

#### get specific row

In [40]:
arr[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[:,5]

array([ 6, 16])

In [45]:
arr[0,0] = 0    # to overwrite any columns or rows ------------------------------

In [46]:
arr     # prints 

array([[ 0,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

## Initializing different types of arrays 

In [50]:
# all zeros matrix

np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [57]:
# all one's matrix 

np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [60]:
# any other numbers 

# syntax  = np.full((row,columns), the number)
np.full((2,3),22)

array([[22, 22, 22],
       [22, 22, 22]])

In [64]:
# random decimal values 

np.random.rand(2,3)

array([[0.55272798, 0.37806685, 0.49730324],
       [0.15165316, 0.04024177, 0.45063224]])

In [68]:
# random integer values 
# syntax= np.random.randint(max number or the range, size = (row, column))
np.random.randint(10, size = (3,2))

array([[3, 8],
       [3, 1],
       [3, 0]])

In [74]:
# indentity matrix 

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Repeat the array 


In [87]:
array1 = np.array([[1,2,3,4]])
r1 = np.repeat(array1, 2, axis = 0) # syntax => np.array(name of the array, how many times to repeat, axis = 0 (vertically repeats)or 1(horizontally repeatation ))
print(r1)

[[1 2 3 4]
 [1 2 3 4]]


### Problem1 : display the following list of matrix 

In [96]:
#  1  1  1  1  1
#  1  0  0  0  1
#  1  0  9  0  1
#  1  0  0  0  1
#  1  1  1  1  1


# solution ------>


output = np.ones((5,5))
#print(output)
z = np.zeros((3,3))
#print(z)

z[1,1] = 9
output[1:4,1:4]= z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying the arrays...................... 

In [107]:
FirstArray = np.array([1,2,3,4])



#SecondArray = FirstArray
#print(SecondArray)

#SecondArray[0] = 100
#FirstArray  

# _______from above -----> the 0th element changed in both arrays_____________ 

# -----------be careful about this while copying the arrays elements ----------- 

SecondArray = FirstArray.copy()

SecondArray[0] = 100
print(FirstArray)
print(SecondArray)

# ____________ solved___________________________ '_'



[1 2 3 4]
[100   2   3   4]


# _____________Mathematics_______

In [111]:
# let us take two arrays to perform operations in mathematics section  _______ 

x = np.array([1,2,3,4,5])
x+2
x*2
x/2
x-1

# hence -----------arithmatics problems can be solved directly -------------------



array([0, 1, 2, 3, 4])

In [112]:
# for sin() values

np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### Linear Algebra

In [ ]:
#____________ matrix multiplication ________________

y = np.random.randint(7, size =(2,3))
z = np.random.randint(8, size =(3,2))


np.matmul(y,z)   # -----> matrix multiplication syntax 


In [118]:
#___________Matrix Determinant___________________

c = np.identity(3)

np.linalg.det(c)  #------> here's the determinant syntax -------
# note : determinant value of identity matrix is 0     '_'

1.0

## Statistics

In [121]:
stats = np.array([[1,2,3],[4,5,6]])
stats

# ________min value_____


np.min(stats, axis=0)  


array([1, 2, 3])

In [126]:
# ______max value_______

# np.max(stats)  # -> shows of whole array

np.max(stats,axis = 0)  

array([4, 5, 6])

In [130]:
# ____________sum_______________

np.sum(stats) # finds the sum of whole array

np.sum(stats, axis =1)
np.sum(stats, axis =0)

array([5, 7, 9])

# Reorganizing arrays 


In [145]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)  #----finds the dimension 


#  ------to reshape the above array -------

#after = before.reshape((4,2))
#after = before.reshape((8,1))
after = before.reshape((2,4))
after

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Vertically Stacking Vectors 

In [147]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])    # vertically stacked 

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontally Stacking

In [149]:
h1 = np.array([2,4])
h2 = np.array([5,10])

np.hstack([h1,h2,h2,h1])

array([ 2,  4,  5, 10,  5, 10,  2,  4])

# __ Miscellaneous__

##### Load data from a file 

In [172]:
fileData = np.genfromtxt('data.txt',delimiter = ',')
fileData = fileData.astype('int32')
fileData

array([[  1,   5,   7,   9,  11,  13,  15,  16,   2,   4],
       [ 45,  23,  46,  78,  49,  62,  85,  78,   5,  32],
       [ 32,  35,  39,  37,  95,  65,  87,  65, 188,  45]])

##### Bolean Masking and Advanced Indexing 

In [161]:
fileData > 10  
fileData >= 10
#.....
# or other equalities 

array([[False, False, False, False,  True,  True,  True,  True, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [166]:
# _____ indexin'____

fileData [fileData>10]    #shows data greater than 10 


array([ 11,  13,  15,  16,  45,  23,  46,  78,  49,  62,  85,  78,  32,
        32,  35,  39,  37,  95,  65,  87,  65, 188,  45])

In [175]:
#____also ---->

np.any(fileData >20, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [178]:
#----------- define range-------

((fileData >0) & (fileData<20))

# also values 

fileData[((fileData >0) & (fileData<20))]


# using not gate(~) ---> reverse

(~(fileData >0) & (fileData<20)) 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

## That's It Myan !